[config]
# 1:debug 2:staging 3:demo/alpha 4:production
status = 1
release_date = "20250418"
listeners = [
    { address = "127.0.0.1", port = 8081 }
]
# relative from executeable program or use absolute path
dir_public_path = "../../public"
# relative from executeable program or use absolute path
dir_public_path_upload = "../../public/upload"

[extra]
dir_public_path_upload_extra = [
    "a", "b", "i"
]